config/routes.rb
Scheduler::Application.routes.draw do

  root :to => 'welcome#index'

  post "user/modify" => "users#modify"
  get "welcome/index" => "welcome#index"
  resources :candidates
  resources :recruiters
  resources :events
  resources :messages
  post "event/addcandidate" => "events#addcandidate"
  post "event/create" => "events#create"
  post "event/update" => "events#update"
  post "event/confirm" => "events#confirm"
  post "event/delete" => "events#delete"
  post '/logout' => "welcome#logout"
  post '/message/create' => "message#create"
  post "recruiter/create" => "recruiters#create"
  post "candidate/create" => "candidates#create"
  post "recruiter/:id/add_candidate" => "recruiters#add_candidate"
  post "recruiter/:id/message_candidate" => "recruiters#message_candidate"
  post "candidate/:id/add_recruiter" => "candidates#add_recruiter"
  get "recruiter/:id/view/:profile_id" => "recruiter#view"
  get "candidate/:id/view/:profile_id" => "candidate#view"
  get "welcome/index" => "welcome#index"
  get "recruiter/get_candidates" => "recruiter#get_candidates"
  get "candidate/:id/list" => "candidates#list", as: 'list_candidate'
  get "candidate/:id/calendar" => "candidates#calendar", as: 'calendar_candidate'
  get "message/:type/:id" => "message#index", as: 'message'
  get "recruiter/:id/mailbox/:type" => "recruiters#mailbox", as: 'recruiter_mailbox'
  get "message/show/:type/:user_id/:id" => "message#show", as: 'message_show'
  get "candidate/:id/mailbox/:type" => "candidates#mailbox", as: 'candidate_mailbox'
  get "recruiter/:id/search" => "recruiters#search", as: 'recruiter_search'
  get "candidate/:id/search" => "candidates#search", as: 'candidate_search'
  get "recruiter/search" => "recruiters#search"
  get "candidate/search" => "candidates#search"
  get "welcome/show" => "welcome#show"
  get "event/show_candidate/:id" => "events#show_candidate"
  get "event/show/:id" => "events#show", as: 'events_show'
  get "recruiter/:id/list" => "recruiters#list", as: 'list_recruiter'
  get "recruiter/:id/calendar" => "recruiters#calendar", as: 'calendar_recruiter'
  get "welcome/forgotpassword" => "welcome#forgotpassword"
  get "welcome/reset_password" => "welcome#reset_password"
  match "welcome/show", :to => redirect("welcome/show")

  match 'login', :to => redirect('/welcome/index')
  match 'welcome', :to => redirect('/welcome/index')

end

app/models/message.rb
class Message < ActiveRecord::Base
   attr_accessible :title, :from, :to, :content, :unread
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
    def index
      @type = params[:type]
      @from = params[:id]
      @user = Recruiter.find_by_username(@from)
      if @user.nil?
        @user = Candidate.find_by_username(@from)
      end
    end

    def create
      new_message_hash = {:title => params[:title], :from => params[:from], :to => params[:to], :content => params[:content]}
      Message.create! new_message_hash
      if params[:type] == "recruiter"
        redirect_to recruiter_mailbox_path(params[:from], "inbox")
      else
        redirect_to candidate_mailbox_path(params[:from], "inbox")
      end
    end

    def show
      @type = params[:type]
      @user = params[:user_id]
      @message = Message.find(params[:id])
    end

end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/message/index.html.erb
<div class = "row main-page">
  <div class = "small-1 columns user-icon">
    <%= link_to raw('<i class="fi-home profile-icon"></i>'), candidate_path %>
    <p>Home</p>
    <%= link_to raw('<i class="fi-calendar profile-icon"></i>'), calendar_candidate_path %>
    <p>Calendar</p>
    <%= link_to raw('<i class="fi-list-thumbnails profile-icon"></i>'), list_candidate_path, :id=>"List"%>
    <p>Contacts</p>
    <%= link_to raw('<i class="fi-mail profile-icon active-icon"></i>'), candidate_path %>
    <p>Messages</p>
    <%= link_to raw('<i class="fi-wrench profile-icon"></i>'), candidate_path %>
    <p>Settings</p>
  </div>
  
  <div class = "small-5 columns">
	<div class = "row page-title">
      <div class = "small-12 columns">
        <h2> Create a Message </h2>
      </div>
    </div>
	
	<form action="/message/create" id="create_form" method="post">
      <h5>Title:</h5>
      <input type="text" id="title" name="title">
      <input type="hidden" id="from" name="type" value="<%= @type %>">
      <input type="hidden" id="from" name="from" value="<%= @user.username %>">
      <h5>To:</h5>
      <input type="text" id="to" name="to">
      <h5>Content:</h5>
      <textarea id="content" name="content"></textarea>
      <input class = "button alert" type="submit" id="submit" value="Create">
      <input class = "button alert" type="submit" id="cancel" value="Cancel">
    </form>
  </div>
   
  <div class = "small-6 columns">
  </div>
</div>
<script>
$("#cancel").click( function () {
    $("#create_form").attr("action", "/<%= @type %>/<%= @user.username %>/mailbox/inbox");
    $("#create_form").attr("method", "get");
});
</script>

app/views/message/show.html.erb
<div class = "row">

 <div class = "large-1 columns user-icon">
  <%= link_to raw('<i class="fi-home profile-icon"></i>'), recruiter_path %>
  <%= link_to raw('<i class="fi-list-thumbnails profile-icon"></i>'), list_recruiter_path, :id=>"List" %>
  <%= link_to raw('<i style="display: inline-block;" class="fi-calendar profile-icon"></i>'), calendar_recruiter_path %>
   <%= link_to raw('<i style="display: inline-block;" class="fi-mail profile-icon"></i>'), candidate_mailbox_path(@user, "inbox") %>
    <%= link_to raw('<i class="fi-wrench profile-icon"></i>'), "/candidates/#{@user}/edit", :id=>"Edit" %>
  </div>

<label>Title</label>
<h6><%= @message.title %></h6>

<div>
<label>From</label>
  <%= @message.from %>
</div>
<br>
<div>
<label>Content: </label>
  <%= @message.content %>
</div>
</div>