config/routes.rb
Scheduler::Application.routes.draw do

  root :to => 'welcome#index'

  post "user/modify" => "users#modify"
  get "welcome/index" => "welcome#index"
  resources :candidates
  resources :recruiters
  resources :events
  resources :messages
  post "event/addcandidate" => "events#addcandidate"
  post "event/create" => "events#create"
  post "event/update" => "events#update"
  post "event/confirm" => "events#confirm"
  post "event/delete" => "events#delete"
  post '/logout' => "welcome#logout"
  post '/message/create' => "message#create"
  post "recruiter/create" => "recruiters#create"
  post "candidate/create" => "candidates#create"
  post "recruiter/:id/add_candidate" => "recruiters#add_candidate"
  post "recruiter/:id/message_candidate" => "recruiters#message_candidate"
  post "candidate/:id/add_recruiter" => "candidates#add_recruiter"
  get "recruiter/:id/view/:profile_id" => "recruiter#view"
  get "candidate/:id/view/:profile_id" => "candidate#view"
  get "welcome/index" => "welcome#index"
  get "recruiter/get_candidates" => "recruiter#get_candidates"
  get "candidate/:id/list" => "candidates#list", as: 'list_candidate'
  get "candidate/:id/calendar" => "candidates#calendar", as: 'calendar_candidate'
  get "message/:type/:id" => "message#index", as: 'message'
  get "recruiter/:id/mailbox/:type" => "recruiters#mailbox", as: 'recruiter_mailbox'
  get "message/show/:type/:user_id/:id" => "message#show", as: 'message_show'
  get "candidate/:id/mailbox/:type" => "candidates#mailbox", as: 'candidate_mailbox'
  get "recruiter/:id/search" => "recruiters#search", as: 'recruiter_search'
  get "candidate/:id/search" => "candidates#search", as: 'candidate_search'
  get "recruiter/search" => "recruiters#search"
  get "candidate/search" => "candidates#search"
  get "welcome/show" => "welcome#show"
  get "event/show_candidate/:id" => "events#show_candidate"
  get "event/show/:id" => "events#show", as: 'events_show'
  get "recruiter/:id/list" => "recruiters#list", as: 'list_recruiter'
  get "recruiter/:id/calendar" => "recruiters#calendar", as: 'calendar_recruiter'
  get "welcome/forgotpassword" => "welcome#forgotpassword"
  get "welcome/reset_password" => "welcome#reset_password"
  match "welcome/show", :to => redirect("welcome/show")

  match 'login', :to => redirect('/welcome/index')
  match 'welcome', :to => redirect('/welcome/index')

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @candidate = Candidate.new
    if not session[:authenticated_user].nil?
      sessname = session[:authenticated_user]
      candidate = Candidate.find_by_username(sessname)
      recruiter = Recruiter.find_by_username(sessname)
      if not candidate.nil?
        redirect_to candidate_path(candidate.username)
      elsif not recruiter.nil?
        redirect_to recruiter_path(recruiter.username)
      end
    end
  end

  def show
    Rails.logger.debug params[:userid]
    foundRecruiter = Recruiter.find_by_username(params[:userid])
    foundCandidate = Candidate.find_by_username(params[:userid])
    if not foundRecruiter.nil?
      foundUser = foundRecruiter
      #redirect_to recruiter_show_path
      redirectPath = recruiter_path(foundRecruiter.username)
    elsif not foundCandidate.nil?
      foundUser = foundCandidate
      #redirect_to candidate_show_path
      redirectPath = candidate_path(foundCandidate.username)
    else
      flash[:notice] = "Username not found"
      redirect_to welcome_index_path and return
    end
    if foundUser.password != params[:password]
      flash[:notice] = "Password was incorrect, please try again"
      redirect_to welcome_index_path and return
    else
      session[:authenticated_user] = foundUser.username
    end
    redirect_to redirectPath
  end

  def logout
    session[:authenticated_user] = nil
    redirect_to welcome_index_path
  end


  def reset_password
  #Check to see if they are a valid user and what kind they are
  # Get a userid for the email address then check to see if the information is nil
    user_email = params[:email]
    type = ""
    user = ""
    if not Recruiter.find_by_email(user_email).nil?
     type = "recruiter"
     user = Recruiter.find_by_email(user_email)
    elsif not Candidate.find_by_email(user_email).nil?
      type = "candidate"
      user = Candidate.find_by_email(user_email)
    else
      flash[:notice] = "No user associated with this email address: #{user_email} "
      redirect_to welcome_index_path and return
    end
    newPass = make_new_password(user, type)
    message = "Hello #{user.username}, \n Your password for InterviewScheduler has been reset to: #{newPass}
      Please login with the above temporary password and edit your user information to another password."
    UserMailer.forgot_password(user_email, message).deliver
    flash[:notice] = "You have been been emailed a temporary password at #{user_email}"
    redirect_to welcome_index_path
  end

  def make_new_password(user, type)
    newPass = SecureRandom.base64()
    user.password = newPass
    user.save!
    return newPass
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/forgotpassword.html.erb
<div class = "row">
<div class = "small-2 columns"></div>
<div class = "small-8 columns">
<h4> Forgot your password? </h4>
<form action="/welcome/reset_password" method="get" id="inputform">
					  <label>Email </label>
                      <input type="text" name="email" value="Email">

                      <input type="submit" class="button" value="Retrieve">

</form>
</div>
<div class = "small-2 columns"></div>
</div>

app/views/welcome/index.html.erb
<header class = "top-header">
  <div class = "row free-container">
      <div class = "twelve columns" >
          <div class = "free">FREE</div>
      </div>
    </div>

    <div class = "row banner">
      <div class = "twelve columns">
          <h1> PLAN, ORGANIZE & MANAGE INTERVIEWS </h1>
          <h4> Easy way to <b>effectively</b> coordinate interviews for both the recruiter and the candidate.</h4>
      </div>
    </div>
</header>

<div class = "row icon-row" >
  <div class = "large-1 columns"> </div>
  <div class = "large-2 columns" id = "icon-active">
    <i class="fi-compass" id = "bottom-icon"></i>
    <h2>Get Started</h2>
  </div>
  <div class = "large-2 columns">
    <i class="fi-megaphone" id ="bottom-icon"></i>
    <h2>Search Candidates</h2>
  </div>
  <div class = "large-2 columns">
    <i class="fi-address-book" id ="bottom-icon"></i>
    <h2>Manage Interviews</h2>
  </div>
  <div class = "large-2 columns">
    <i class="fi-clock" id ="bottom-icon"></i>
    <h2>Set Time</h2>
  </div>
  <div class = "large-2 columns">
    <i class="fi-dollar" id ="bottom-icon"></i>
    <h2>Get Jobs</h2>
  </div>
  <div class = "large-1 columns"></div>
</div>

<div class = "row" id = "main-form">
  <div class = "large-3 columns"></div>
  <div class = "large-6 columns">
    <div class = "form-wrapper" >
      <h4> CREATE AN ACCOUNT </h4>

      <% if flash[:notice] == "createError" %>
        <div id="error_explanation">
          <ul>
            <li>Error: User Exists</li>
          </ul>
        </div>
      <% end %>
      
      <%= form_for(@candidate) do |f| %>
        
        <select id="acctype" name="acctype" class = "large">
          <option value="candidate">Candidate</option>
          <option value="recruiter">Recruiter</option>
        </select>
            
        <div class="field">
          <%= f.label "Username" %>
          <%= f.text_field :username %>
        </div>
        <div class="field">
          <%= f.label "Name" %>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label "Email" %>
          <%= f.text_field :email %>
        </div>
        <div class ="field">
          <%= f.label "Password" %>
          <%= f.password_field :password %>
        </div>
        <div class="field">
          <label id="companyLabel" style="display:none;">Company </label>
          <input type="hidden" id="character_company" name="company" value="">
        </div>
        <div class="actions">
          <input type="submit" id="subutton" class="large button" value="Create">
        </div>
      <% end %>
    </div>
  </div>
  <div class = "large-3 columns">
  </div>
</div>

<script>
$( "#acctype").change( function() {
   selected = $("#acctype").val();
   if(selected == "recruiter") {
     $( "#companyLabel").css("display", "block");
     $( "#character_company").attr("type", "text");
   } else {
     $( "#companyLabel").css("display", "none");
     $( "#character_company").attr("type", "hidden");
   }
}
)

$( "#subutton" ).click( function() {
    selectVal = $("#acctype").val();
    if(selectVal == "recruiter") {
       $("#new_candidate").attr("method", "post");
       $("#new_candidate").attr("action", "/recruiter/create");
    } else if(selectVal == "candidate") {
       $("#new_candidate").attr("method", "post");
       $("#new_candidate").attr("action", "/candidate/create");
    } else {
       alert("Please Select either Recruiter or Candidate");
       $("#new_candidate").attr("method", "get");
       $("#new_candidate").attr("action", "/welcome/index");
    }
 }
)
</script>

app/views/welcome/index.html.haml
%header.top-header
  .row.free-container
    .twelve.columns
      .free FREE
  
  .row.banner
    .twelve.columns
      %h1 PLAN, ORGANIZE & MANAGE INTERVIEWS
      %h4 Easy way to effectively coordinate interviews for both the recruiter and the candidate

.row
.four.columns
.four.columns
  .form-wrapper
    = form_tag candidates_path do
      %h4 CREATE AN ACCOUNT
      .field
        = label :candidate, :username, 'Username'
        = text_field :candidate, 'username'
      .field
        = label :candidate, :password, 'Password'
        = password_field :candidate, 'password'
      .field
        = label :candidate, :name, 'Your Name'
        = text_field :candidate, 'name'
      .field
        = label :candidate, :email, 'Email'
        = text_field :candidate, 'email'
      = submit_tag 'Create'


alskfjsldkfj
.four.columns