config/routes.rb
Scheduler::Application.routes.draw do

  root :to => 'welcome#index'

  post "user/modify" => "users#modify"
  get "welcome/index" => "welcome#index"
  resources :candidates
  resources :recruiters
  resources :events
  resources :messages
  post "event/addcandidate" => "events#addcandidate"
  post "event/create" => "events#create"
  post "event/update" => "events#update"
  post "event/confirm" => "events#confirm"
  post "event/delete" => "events#delete"
  post '/logout' => "welcome#logout"
  post '/message/create' => "message#create"
  post "recruiter/create" => "recruiters#create"
  post "candidate/create" => "candidates#create"
  post "recruiter/:id/add_candidate" => "recruiters#add_candidate"
  post "recruiter/:id/message_candidate" => "recruiters#message_candidate"
  post "candidate/:id/add_recruiter" => "candidates#add_recruiter"
  get "recruiter/:id/view/:profile_id" => "recruiter#view"
  get "candidate/:id/view/:profile_id" => "candidate#view"
  get "welcome/index" => "welcome#index"
  get "recruiter/get_candidates" => "recruiter#get_candidates"
  get "candidate/:id/list" => "candidates#list", as: 'list_candidate'
  get "candidate/:id/calendar" => "candidates#calendar", as: 'calendar_candidate'
  get "message/:type/:id" => "message#index", as: 'message'
  get "recruiter/:id/mailbox/:type" => "recruiters#mailbox", as: 'recruiter_mailbox'
  get "message/show/:type/:user_id/:id" => "message#show", as: 'message_show'
  get "candidate/:id/mailbox/:type" => "candidates#mailbox", as: 'candidate_mailbox'
  get "recruiter/:id/search" => "recruiters#search", as: 'recruiter_search'
  get "candidate/:id/search" => "candidates#search", as: 'candidate_search'
  get "recruiter/search" => "recruiters#search"
  get "candidate/search" => "candidates#search"
  get "welcome/show" => "welcome#show"
  get "event/show_candidate/:id" => "events#show_candidate"
  get "event/show/:id" => "events#show", as: 'events_show'
  get "recruiter/:id/list" => "recruiters#list", as: 'list_recruiter'
  get "recruiter/:id/calendar" => "recruiters#calendar", as: 'calendar_recruiter'
  get "welcome/forgotpassword" => "welcome#forgotpassword"
  get "welcome/reset_password" => "welcome#reset_password"
  match "welcome/show", :to => redirect("welcome/show")

  match 'login', :to => redirect('/welcome/index')
  match 'welcome', :to => redirect('/welcome/index')

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  
  attr_accessible :email, :name, :username, :password, :phone, :attach, :pic
  has_and_belongs_to_many :recruiters

  has_attached_file :pic,
    :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :default_path => ":rails_root/public/system/:class/:attachment/:id/:style/no-pic.jpg",
    :path => ":rails_root/public/system/:class/:attachment/:id/:style/:filename",
    :default_url => "/assets/no-pic.jpg",
    :url => "/system/:class/:attachment/:id/:style/:filename"

  has_attached_file :attach,
    :default_path => ":rails_root/public/system/:class/:attachment/:id/:style/no-attach.jpg",
    :path => ":rails_root/public/system/:class/:attachment/:id/:style/:filename",
    :default_url => "/assets/no-attach.png",
    :url => "/system/:class/:attachment/:id/:style/:filename"

end

app/controllers/candidates_controller.rb
class CandidatesController < UsersController

  before_filter :except => [:create] {|c|
    c.authorize params[:id], :candidate
  }

  def index
  end


  def mailbox
    @candidate = params[:id]
    @type = params[:type]
    @mail = get_mail(@candidate, @type)
  end

  def create
    Rails.logger.debug params
    #Creates a candidate.
    #redirects to add_user in user_controller. The add_user actually creates the user
    success = add_user(params[:candidate], :Candidate)
    if success
      #If the candidate was successfully created, redirect to the correct candidate profile page.
      #Otherwise, redirect to the front page with error that user already exists or validation was incorrect.
      redirect_to candidate_path(params[:candidate][:username])
    else
      flash[:notice] = "createError"
      redirect_to welcome_index_path
    end
  end

  def edit
    #Shows the corresponding edit page.
    @candidate = Candidate.find_by_username(params[:id])
  end

  def view
    @profile = Recruiter.find_by_username(params[:profile_id])
    @src_id = params[:id]
  end

  def search
    @keyword = params[:keyword]
    @candidate = params[:candidate]
    @recruiters = search_helper(params[:keyword], "candidate")
  end

  def update
    #perfoms the actual update.
    @candidate = Candidate.find_by_username(params[:id])
    #Redirects to the modify in user_controller.  Just updates the specific entries for a candidate
    modify(@candidate, :candidate)
    #Redirects upon update to the candidate profile page.
    redirect_to candidate_path(@candidate.username)
  end

  def show
    #Redirects to the candidate view
    @candidate = Candidate.find_by_username(params[:id])
    @events = Event.find(:all, :conditions=>["pending_id = ? and end_at > ?", @candidate.username, DateTime.now], :order=>"start_at ASC", :limit=>5)
    @requests = Event.find(:all, :conditions=>["pending_id = ? and end_at > ? and (candidate_id = '' or candidate_id IS NULL)", @candidate.username, DateTime.now], :order=>"start_at ASC", :limit=>5)
  end

  def list
    @candidate = Candidate.find_by_username(params[:id])
    @recruiters = @candidate.recruiters
  end

  def calendar
    @candidate = Candidate.find_by_username(params[:id])
    @events =  Event.find(:all, :conditions=>["pending_id = ?", @candidate.username])
  end

  def add_recruiter
    @candidate = Candidate.find_by_username(params[:id])
    @recruiter = Recruiter.find_by_username(params[:recruiter])
    if @recruiter
      @candidate.recruiters << @recruiter
      redirect_to list_candidate_path(@candidate.username)
    else
      flash[:error] = "Could not find the recruiter with that username"
      redirect_to list_candidate_path(@candidate.username)
    end
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper

  def show_event_info(event, with)
    date = mdyFormat(event.start_at)
    if event.candidate_id.nil?
      pending = "Pending"
    else
      pending = "Scheduled"
    end
    title = event.name
    if title.nil? or title == ""
      title = "NO TITLE"
    end
    [title, with, pending, date]
  end

  def show_request_info(request, with)
    date = mdyFormat(request.start_at)
    if with.nil? or with == ""
      with = "UNKNOWN"
    end
    title = request.name
    if title.nil? or title == ""
      title = "NO TITLE"
    end
    [title, with, date]
  end

  def mdyFormat(date)
    date.strftime("%m/%d/%y")
  end

end

app/views/candidates/calendar.html.erb
<%= javascript_include_tag "application" %>

<div class = "row main-page">
  <div class = "small-1 columns user-icon">
    <%= link_to raw('<i class="fi-home profile-icon"></i>'), candidate_path %>
    <p>Home</p>
    <%= link_to raw('<i class="fi-calendar profile-icon active-icon"></i>'), calendar_candidate_path %>
    <p>Calendar</p>
    <%= link_to raw('<i class="fi-list-thumbnails profile-icon"></i>'), list_candidate_path, :id=>"List"%>
    <p>Contacts</p>
    <%= link_to raw('<i class="fi-mail profile-icon"></i>'), candidate_mailbox_path(@candidate.username, "inbox") %>
    <p>Messages</p>
    <%= link_to raw('<i class="fi-wrench profile-icon"></i>'), "/candidates/#{@candidate.username}/edit", :id=>"Edit"%>
    <p>Settings</p>
  </div>
  <div class = "large-7 columns">
    <div id = "calendar">
    </div>
  </div>
  <div class = "large-3 columns calendar-explanation">

    <div class = "row">
    <div class = "large-2 columns">
      <div id = "pending-block"></div>
    </div>
    <div class = "large-10 columns setting-saying">
      <p><b>Past Interview</b> </br>[Interview Date Passed]</p>
    </div>
  </div>

  <div class = "row">
    <div class = "large-2 columns">
      <div id = "no-block"></div>
    </div>
    <div class = "large-10 columns setting-saying">
      <p><b>Pending</b> </br>[No Candidate Confirmed]</p>
    </div>
  </div>

  <div class = "row">
    <div class = "large-2 columns">
      <div id = "confirm-block"></div>
    </div>
    <div class = "large-10 columns setting-saying">
      <p><b>Confirmed</b> </br>[Confirmed Interview Timeslot]</p>
    </div>
  </div>
  </div>
  <div class = "large-1 columns">
  </div>
</div>
<script type='text/javascript'>

  $(document).ready(function() {
    $('#calendar').fullCalendar({
       eventClick: function(calEvent, jsEvent, view) {
        var title = calEvent.id
        window.location.href = "/event/show/" + title + "?from_id=<%= @candidate.username %>";
      },
      editable: true,
      events: [
          <% @events.each do |event| %>
          {
             id : "<%= event.id %>",
             title : "<%= event.name %>",
             start: "<%= event.start_at.strftime('%Y-%m-%d') %>",
             end: "<%= event.end_at.strftime('%Y-%m-%d') %>",
             <% if event.start_at.to_i  < Time.now.to_i %>
                className: 'customBlack'
              <% elsif not (event.pending_id.nil? or event.pending_id == "") and not (event.candidate_id.nil? or event.pending_id == "")%>
                className: 'customGreen'
              <% else %>
                className: 'customRed'
             <% end %>
           },
          <% end %>
      ],

    });

  });
</script>

app/views/candidates/edit.html.erb
<div class = "row main-page">
  <div class = "small-1 columns user-icon">
    <%= link_to raw('<i class="fi-home profile-icon"></i>'), candidate_path %>
    <p>Home</p>
    <%= link_to raw('<i class="fi-calendar profile-icon"></i>'), calendar_candidate_path %>
    <p>Calendar</p>
    <%= link_to raw('<i class="fi-list-thumbnails profile-icon"></i>'), list_candidate_path, :id=>"List"%>
    <p>Contacts</p>
    <%= link_to raw('<i class="fi-mail profile-icon"></i>'), candidate_mailbox_path(@candidate.username, "inbox") %>
    <p>Messages</p>
    <%= link_to raw('<i class="fi-wrench profile-icon active-icon"></i>'), "/candidates/#{@candidate.username}/edit", :id=>"Edit"%>
    <p>Settings</p>
  </div>


  <div class = "small-5 columns">
    <div class = "row page-title">
      <div class = "small-12 columns">
        <h2> Settings </h2>
      </div>
    </div>
    <%= content_tag :h4, "Edit page for #{@candidate.name}" %>
    <%= form_for @candidate, :html => {:id => "new_candidate", :multipart => true }, url: "/candidates/#{@candidate.username}", method: :put do |f| %>
      <div class="field">
        <%= f.label "Name" %>
        <%= f.text_field :name, :value=>"#{@candidate.name}" %>
      </div>
      <div class="field">
        <%= f.label "Email" %>
        <%= f.text_field :email, :value=>"#{@candidate.email}" %>
      </div>
      <div class ="field">
        <%= f.label "Password" %>
        <%= f.password_field :password, :value=>"#{@candidate.password}" %>
      </div>
      <div class="field">
        <%= f.label "Area of Interest" %>
        <%= f.text_field :area_of_interest, :value=>"#{@candidate.area_of_interest}" %>
      </div>
      <div class="field">
        <%= f.label "Education" %>
        <%= f.text_field :education, :value=>"#{@candidate.education}" %>
      </div>
      <div class="field">
        <%= f.label "Location" %>
        <%= f.text_field :location, :value=>"#{@candidate.location}" %>
      </div>
      <div class="field">
        <%= f.label "Summary" %>
        <%= f.text_field :summary, :value=>"#{@candidate.summary}" %>
      </div>
      <div class="attachment">
        <%= f.label "Attachment" %>
        <%= f.file_field :attach %>
        <br/>
      </div>
     <div class="pic">
       <br/>
       <%= f.label "Picture" %>
       <%= f.file_field :pic %>
       <br/>
     </div>

     <br/>

     <div class="actions">
       <input type="submit" id="subutton" class="button small alert" value="Update">
     </div>
    <% end %>
  </div>

  <div class = "small-6 columns">
  </div>
</div>

app/views/candidates/list.html.erb
<div class = "row main-page">
  <div class = "small-1 columns user-icon">
    <%= link_to raw('<i class="fi-home profile-icon"></i>'), candidate_path %>
    <p>Home</p>
    <%= link_to raw('<i class="fi-calendar profile-icon"></i>'), calendar_candidate_path %>
    <p>Calendar</p>
    <%= link_to raw('<i class="fi-list-thumbnails profile-icon active-icon"></i>'), list_candidate_path, :id=>"List"%>
    <p>Contacts</p>
    <%= link_to raw('<i class="fi-mail profile-icon"></i>'), candidate_mailbox_path(@candidate.username, "inbox") %>
    <p>Messages</p>
    <%= link_to raw('<i class="fi-wrench profile-icon"></i>'), "/candidates/#{@candidate.username}/edit", :id=>"Edit"%>
    <p>Settings</p>
  </div>

  <div class = "large-6 columns">
  <div class = "row page-title">
      <div class = "small-12 columns">
        <h2> List of Associated Recruiters </h2>
      </div>
    </div>
    <table id="recruiters">
      <tr>
        <th>Full Name</th>
        <th>Username</th>
        <th>Email</th>
      </tr>
      <% @recruiters.each do |recruiter|%>
        <tr>
          <td id="name"><%=recruiter.name%></td>
          <td id="username"><%=recruiter.username%></td>
          <td id="email"><%=recruiter.email%></td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class = "large-3 columns search-feature">
  <h3> Associate Recruiter </h3>
  <% if flash[:error] %>
    <%= flash[:error] %>
    </br></br>
  <% end %>
  <h6> Add Recruiter </h6>
  <%= form_tag("add_recruiter", method: "post") do %>
      <%= text_field_tag(:recruiter, nil, :id=>"recruiter_username") %>
      <%= submit_tag("Add", class: "button alert")%>
  <% end %>
   <h6> Search by name or username </h6>
  <%= form_tag("search", method: "get") do %>
     <input type="hidden" id="candidate" name="candidate" value="<%= @candidate.username %>">
     <input type="text" id="keyword" name="keyword">
     <input type="submit" class ="button alert" id="Search" value="Search">
  <% end %>
  </div>
  <div class = "large-2 columns">
  </div>
</div>

app/views/candidates/mailbox.html.erb
<div class = "row main-page">
  <div class = "small-1 columns user-icon">
    <%= link_to raw('<i class="fi-home profile-icon"></i>'), candidate_path %>
    <p>Home</p>
    <%= link_to raw('<i class="fi-calendar profile-icon"></i>'), calendar_candidate_path %>
    <p>Calendar</p>
    <%= link_to raw('<i class="fi-list-thumbnails profile-icon"></i>'), list_candidate_path, :id=>"List"%>
    <p>Contacts</p>
    <%= link_to raw('<i class="fi-mail profile-icon active-icon"></i>'), candidate_mailbox_path(@candidate, "inbox") %>
    <p>Messages</p>
    <%= link_to raw('<i class="fi-wrench profile-icon"></i>'), "/candidates/#{@candidate}/edit", :id=>"Edit"%>
    <p>Settings</p>
  </div>

  <div class = "small-8 columns">
	<div class = "row page-title">
      <div class = "small-12 columns">
        <h2> Messages </h2>
      </div>
    </div>    
    
    <div class = "row">
	  <div class = "small-12">
		
		<dl class="sub-nav">
  			<dd><a href="/candidate/<%= @candidate %>/mailbox/inbox">Inbox</a></dd>
  			<dd><a href="/candidate/<%= @candidate %>/mailbox/outbox">Outbox</a></dd>
		</dl>
	    <% if @type == "inbox" %>
		  
		<% else %>
		
		<% end %>	
	  </div>
	</div> 
  <div class = "row">
	<div class = "small-12">
  <table id = "mailbox">
    <thead>
      <tr>
        <th id = "messenger"> Messenger </th>
        <th id = "title"> Title </th>
        <th id = "content"> Content </th>
      <tr>
    </thead>
  <tbody>
    <% @mail.each do |mail| %>
      <tr>
        <td>
	      <% if @type == "inbox" %>
	        <%= mail.from %>
	      <% else %>
	        <%= mail.to %>
	      <% end %>
	    </td>
	    <td>
			<%= mail.title %>
		</td>
		<td>
			<%= mail.content %>
		</td>
      </tr>
    <% end %>
  </tbody>
  </table>
    </div>
  </div>
  <button class="small button alert" id="compose_button">Compose </a>
  </div>
  <div class = "small-3">
  </div>

</div>

<script>
  $("#compose_button").click( function() {
    window.location.href = "/message/candidate/" + "<%= @candidate %>";
  });
</script>

app/views/candidates/search.html.erb
<div class = "row main-page">
   <div class = "small-1 columns user-icon">
    <%= link_to raw('<i class="fi-home profile-icon"></i>'), candidate_path %>
    <p>Home</p>
    <%= link_to raw('<i class="fi-calendar profile-icon"></i>'), calendar_candidate_path %>
    <p>Calendar</p>
    <%= link_to raw('<i class="fi-list-thumbnails profile-icon  active-icon"></i>'), list_candidate_path, :id=>"List"%>
    <p>Contacts</p>
    <%= link_to raw('<i class="fi-mail profile-icon"></i>'), candidate_mailbox_path(@candidate, "inbox")%>
    <p>Messages</p>
    <%= link_to raw('<i class="fi-wrench profile-icon"></i>'), "/candidates/#{@candidate}/edit", :id=>"Edit"%>
    <p>Settings</p>
  </div>

  <div class = "small-8 columns">
    <div class = "row page-title">
      <div class = "small-12 columns">
        <h2> Search Results</h2>
      </div>
    </div>
    
    <div class = "row">
	  <div class = "small-12 columns"> 
        <table id="candidates">
          <tr>
      		<th>Full Name</th>
      		<th>Username</th>
      		<th>Email</th>
      		<th>Add</th>    
    	  </tr>
  		  <% @recruiters.each do |recruiter|%>
    	    <tr>
      		  <%= form_tag("add_recruiter", method: "post") do %>
      		  	<td id="name"><%=recruiter.name%></td>
      			<%= hidden_field_tag(:recruiter, recruiter.username, :id => "recruiter_username") %>
      			<td id="username"><%=recruiter.username%></td>
      			<td id="email"><%=recruiter.email%></td>
      			<td><%= submit_tag("Add", class: "button small") %></td>
      	      <% end %>
    	    </tr>
  		  <% end %>
  		</table>
	  </div>
	</div>
  </div>

  <div class = "small-3 columns">
  </br></br>   
  <h4> Associate Recruiter </h4>
  <% if flash[:error] %>
    <%= flash[:error] %>
    </br></br>
  <% end %>
  <%= form_tag("add_recruiter", method: "post") do %>
      <%= label_tag(:recruiter, "Recruiter's Username") %>
      <%= text_field_tag(:recruiter, nil, :id=>"recruiter_username") %>
      <%= submit_tag("Add", class: "button alert small") %>
  <% end %>
  <h4>Search</h4>
  <%= form_tag("search", method: "get") do %>
    <%= label_tag("Search by name or username")%>
    <input type="hidden" id="candidate" name="candidate" value="<%= @candidate %>" >
    <input type="text" id="keyword" name="keyword">
    <input type="submit" id="Search" value="Search" class = "button alert small">
  <% end %>

  </div>
  
</div>

app/views/candidates/show.html.erb
<div class = "row main-page">
  <div class = "small-1 columns user-icon">
    <%= link_to raw('<i class="fi-home profile-icon active-icon"></i>'), candidate_path %>
    <p>Home</p>
    <%= link_to raw('<i class="fi-calendar profile-icon"></i>'), calendar_candidate_path %>
    <p>Calendar</p>
    <%= link_to raw('<i class="fi-list-thumbnails profile-icon"></i>'), list_candidate_path, :id=>"List"%>
    <p>Contacts</p>
    <%= link_to raw('<i class="fi-mail profile-icon"></i>'), candidate_mailbox_path(@candidate.username, "inbox") %>
    <p>Messages</p>
    <%= link_to raw('<i class="fi-wrench profile-icon"></i>'), "/candidates/#{@candidate.username}/edit", :id=>"Edit"%>
    <p>Settings</p>
  </div>

  <div class = "small-11 columns">
    <div class = "row page-title">
      <div class = "small-12 columns">
        <h2> Dashboard </h2>
      </div>
    </div>

    <div class = "row">
      <div class = "small-5 columns">
    <div class = "row profile-view">
      <div class = "small-6 columns">
        <%= image_tag @candidate.pic.url(:thumb), id: "profile-picture" %>
      </div>
      <div class = "small-6 columns profile-info">
        <div class = "panel">
        <h5>Username</h5>
        <h6><%= @candidate.username %></h6>
        <h5>Name</h5>
        <h6><%= @candidate.name %></h6>
        <h5>Area of Interest</h5>
        <h6><%= @candidate.area_of_interest %></h6>
        <h5>Education</h5>
        <h6><%= @candidate.education %></h6>
        <h5>Location</h5>
        <h6><%= @candidate.location %></h6>
        </div>
      </div>
    </div>
    <div class = "row">
      <div class = "small-12 columns profile-info-summary">
        <div class = "panel">
          <h5>Summary</h5>
          <h6><%= @candidate.summary %></h6>
        </div>

        <a class = "button alert" id = "resume-button" href="<%= @candidate.attach.url %>">Resume</a>

      </div>
    </div>

      </div>

      <div class = "small-7 columns ">
    <div class = "row request-events">
      <div class = "small-12 columns">
            <h4> Pending Interview Requests </h4>
            <% if @requests.empty? %>
              <p> No pending requests </p>
            <% else %>
              <table id="pending_requests">
        <thread>
          <tr>
            <th>Event Title</th>
            <th>Recruiter</th>
            <th>Date</th>
            <th>Details</th>
          </tr>
        </thread>
        <tbody>
                <% @requests.each do |request|%>
          <% request_info = show_request_info(request, request.recruiter_id)%>
                  <tr>
                    <td id="title"><%= request_info[0] %></td>
          <td id="meet_with"><%= request_info[1] %></td>
          <td id="date"><%= request_info[2] %></td>
                    <td>
            <a class="small button" href="/event/show/<%=request.id%>?from_id=<%=@candidate.username%>">Details</a>
            </td>
                  </tr>
                <% end %>
        </tbody>
              </table>
            <% end %>
          </div>
    </div>
    <div class = "row">
      <div class = "small-12 columns">
        <h4> Upcoming Events </h4>
            <% if @events.empty? %>
              <p> No upcoming events </p>
            <% else %>

        <table id="show-events">
        <thread>
          <tr>
            <th>Event Title</th>
            <th>Recruiter</th>
            <th>Status</th>
            <th>Date</th>
            <th>Details</th>
          </tr>
        </thread>
        <tbody>
                <% @events.each do |event|%>
          <% request_info = show_event_info(event, event.recruiter_id)%>
                  <tr>
                    <td id="title"><%= request_info[0] %></td>
          <td id="meet_with"><%= request_info[1] %></td>
          <td id="status"><%= request_info[2] %></td>
          <td id="date"><%= request_info[3] %></td>
                    <td>
            <a class="small button" href="/event/show/<%=event.id%>?from_id=<%=@candidate.username%>">Details</a>
            </td>
                  </tr>
                <% end %>
        </tbody>
              </table>

            <% end %>
      </div>
    </div>
      </div>

    </div>
  </div>
</div>

app/views/candidates/show.html.haml
%h3 Candidate Profile View
%h3 Welcome, #{@candidate.name}
%h3 Your email address is: #{@candidate.email}