config/routes.rb
Scheduler::Application.routes.draw do

  root :to => 'welcome#index'

  post "user/modify" => "users#modify"
  get "welcome/index" => "welcome#index"
  resources :candidates
  resources :recruiters
  resources :events
  resources :messages
  post "event/addcandidate" => "events#addcandidate"
  post "event/create" => "events#create"
  post "event/update" => "events#update"
  post "event/confirm" => "events#confirm"
  post "event/delete" => "events#delete"
  post '/logout' => "welcome#logout"
  post '/message/create' => "message#create"
  post "recruiter/create" => "recruiters#create"
  post "candidate/create" => "candidates#create"
  post "recruiter/:id/add_candidate" => "recruiters#add_candidate"
  post "recruiter/:id/message_candidate" => "recruiters#message_candidate"
  post "candidate/:id/add_recruiter" => "candidates#add_recruiter"
  get "recruiter/:id/view/:profile_id" => "recruiter#view"
  get "candidate/:id/view/:profile_id" => "candidate#view"
  get "welcome/index" => "welcome#index"
  get "recruiter/get_candidates" => "recruiter#get_candidates"
  get "candidate/:id/list" => "candidates#list", as: 'list_candidate'
  get "candidate/:id/calendar" => "candidates#calendar", as: 'calendar_candidate'
  get "message/:type/:id" => "message#index", as: 'message'
  get "recruiter/:id/mailbox/:type" => "recruiters#mailbox", as: 'recruiter_mailbox'
  get "message/show/:type/:user_id/:id" => "message#show", as: 'message_show'
  get "candidate/:id/mailbox/:type" => "candidates#mailbox", as: 'candidate_mailbox'
  get "recruiter/:id/search" => "recruiters#search", as: 'recruiter_search'
  get "candidate/:id/search" => "candidates#search", as: 'candidate_search'
  get "recruiter/search" => "recruiters#search"
  get "candidate/search" => "candidates#search"
  get "welcome/show" => "welcome#show"
  get "event/show_candidate/:id" => "events#show_candidate"
  get "event/show/:id" => "events#show", as: 'events_show'
  get "recruiter/:id/list" => "recruiters#list", as: 'list_recruiter'
  get "recruiter/:id/calendar" => "recruiters#calendar", as: 'calendar_recruiter'
  get "welcome/forgotpassword" => "welcome#forgotpassword"
  get "welcome/reset_password" => "welcome#reset_password"
  match "welcome/show", :to => redirect("welcome/show")

  match 'login', :to => redirect('/welcome/index')
  match 'welcome', :to => redirect('/welcome/index')

end

app/models/recruiter.rb
class Recruiter < ActiveRecord::Base  
 
  attr_accessible :email, :name, :phone, :password, :company, :username, :attach, :pic

  has_and_belongs_to_many :candidates

  has_attached_file :pic,
    :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :default_path => ":rails_root/public/system/:class/:attachment/:id/:style/no-pic.jpg",
    :path => ":rails_root/public/system/:class/:attachment/:id/:style/:filename",
    :default_url => "/system/no-pic.jpg",
    :url => "/system/:class/:attachment/:id/:style/:filename"

  has_attached_file :attach,
  	:default_path => ":rails_root/public/system/:class/:attachment/:id/:style/no-attach.jpg",
    :path => ":rails_root/public/system/:class/:attachment/:id/:style/:filename",
    :default_url => "/system/no-attach.png",
    :url => "/system/:class/:attachment/:id/:style/:filename"

end

app/controllers/recruiters_controller.rb
require "cgi"

class RecruitersController < UsersController
  before_filter :except => [:create] { |c|
    c.authorize params[:id], :recruiter
  }

  respond_to :json

  def index
    @recruiter=Recruiter.new
  end

  def mailbox
    @recruiter = params[:id]
    @type = params[:type]
    @mail = get_mail(@recruiter, @type)
  end

  def view
    @profile = Recruiter.find_by_username(params[:profile_id])
    @src_id = params[:id]
  end

  def create
    #Creates a new recruiter similar to candidate.
    Rails.logger.debug params
    params[:candidate][:company] = params[:company]
    #Redirects to add_user in user_controller.
    success = add_user(params[:candidate], :Recruiter)
    if success
      #If the user was successfully added, redirect to the user's profile page. Otherwise redirect to front page with error.
      redirect_to recruiter_path(params[:candidate][:username])
    else
      flash[:notice] = "createError"
      redirect_to welcome_index_path
    end
  end

  def edit
    @recruiter = Recruiter.find_by_username(params[:id])
  end

  def update
    @recruiter = Recruiter.find_by_username(params[:id])
    modify(@recruiter, :recruiter)
    redirect_to recruiter_path(@recruiter.username)
  end

  def show
    @recruiter = Recruiter.find_by_username(params[:id])
    @events = Event.find(:all, :conditions=>["recruiter_id = ? and end_at > ?", @recruiter.username, DateTime.now], :order=>"start_at ASC", :limit=>5)
  end

  def search
    @keyword = params[:keyword]
    @recruiter = params[:recruiter]
    @candidates = search_helper(params[:keyword], "recruiter")
  end

  def list
    @recruiter = Recruiter.find_by_username(params[:id])
    @candidates = @recruiter.candidates
  end

  def calendar
    require 'json'
    @recruiter = Recruiter.find_by_username(params[:id])
    @events =  Event.find(:all, :conditions=>["recruiter_id = ?", @recruiter.username])
   end

  def add_candidate
    @recruiter = Recruiter.find_by_username(params[:id])
    @candidate = Candidate.find_by_username(params[:candidate])
    if @candidate
      @recruiter.candidates << @candidate
      redirect_to list_recruiter_path(@recruiter.username)
    else
      flash[:error] = "Could not find the candidate with that username"
      redirect_to list_recruiter_path(@recruiter.username)
    end
  end

  def message_candidate
    message(session[:authenticated_user], params[:candidate], params[:message])
    redirect_to list_recruiter_path(@recruiter.username)
  end
end

app/views/recruiters/calendar.html.erb
<%= javascript_include_tag "application" %>
<%= flash[:notice] %>

<div class = "row main-page">
  <div class = "small-1 columns user-icon">
    <%= link_to raw('<i style="display: inline-block;" class="fi-home profile-icon"></i>'), recruiter_path %>
    <p>Home</p>
    <%= link_to raw('<i style="display: inline-block;" class="fi-calendar profile-icon active-icon"></i>'), calendar_recruiter_path %>
    <p>Calendar</p>
    <%= link_to raw('<i style="display: inline-block;" class="fi-list-thumbnails profile-icon"></i>'), list_recruiter_path, :id=>"List" %>
    <p>Contacts</p>
      <%= link_to raw('<i style="display: inline-block;" class="fi-mail profile-icon"></i>'), recruiter_mailbox_path(@recruiter.username, "inbox") %>
     <p>Messages</p>
    <%= link_to raw('<i class="fi-wrench profile-icon"></i>'), "/recruiters/#{@recruiter.username}/edit", :id=>"Edit" %>
    <p>Settings</p>
  </div>

  <div class = "large-7 columns">
    <div id = "calendar">
    </div>
  </div>

  <div class = "large-3 columns calendar-explanation">

    <div class = "row">
    <div class = "large-2 columns">
      <div id = "pending-block"></div>
    </div>
    <div class = "large-10 columns setting-saying">
      <p><b>Past Interview</b> </br>[Interview Date Passed]</p>
    </div>
  </div>

  <div class = "row">
    <div class = "large-2 columns">
      <div id = "no-block"></div>
    </div>
    <div class = "large-10 columns setting-saying">
      <p><b>Pending</b> </br>[No Candidate confirmed]</p>
    </div>
  </div>

  <div class = "row">
    <div class = "large-2 columns">
      <div id = "confirm-block"></div>
    </div>
    <div class = "large-10 columns setting-saying">
      <p><b>Confirmed</b> </br>[Confirmed Interview Timeslot]</p>
    </div>
  </div>
  </div>
  <div class = "large-1 columns">
  </div>
     </div>
</div>
<div class="popup" id="new_event"><h3>Add an Event</h3>
<form action="/event/create" id="creationForm" method="post">
<label>Title:</label><input class="title" name="title" type="text" id="title">
<label>Invite Candidate </label><input  name="pending_id" type="text" id="pending_id">
<label>Start_Date(m, d, y): </label>
   <div>
   <select id="start_month" name="start_month">
       <option selected value="0">Jan</option>
       <option value="1">Feb</option>
       <option value="2">March</option>
       <option value="3">April</option>
       <option value="4">May</option>
       <option value="5">June</option>
       <option value="6">July</option>
       <option value="7">Aug</option>
       <option value="8">Sept</option>
       <option value="9">Oct</option>
       <option value="10">Nov</option>
       <option value="11">Dec</option>
   </select>
   </div>
      <div>
   <select id="start_date" name="start_date">
       <%  options = []
           (0..31).each do |n|
              dateOption = [n, n]
              options << dateOption
           end %>
        <%= options_for_select(options, 1) %>
    </select>
    </div>
   <div>
   <select id="start_year" name="start_year">
       <option value="2013">2013</option>
       <option value="2014">2014</option>
       <option value="2015">2015</option>
       <option value="2016">2016</option>
    </select>
    </div>

<label>End_Date(m, d, y): </label>
   <div>
   <select id="end_month" name="end_month">
       <option selected value="0">Jan</option>
       <option value="1">Feb</option>
       <option value="2">March</option>
       <option value="3">April</option>
       <option value="4">May</option>
       <option value="5">June</option>
       <option value="6">July</option>
       <option value="7">Aug</option>
       <option value="8">Sept</option>
       <option value="9">Oct</option>
       <option value="10">Nov</option>
       <option value="11">Dec</option>
   </select>
   </div>
   <div>
   <select id="end_date" name="end_date">
       <%  options = []
           (0..31).each do |n|
              dateOption = [n, n]
              options << dateOption
           end %>
        <%= options_for_select(options, 1) %>
    </select>
   </div>
   <div>
   <select id="end_year" name="end_year">
       <option value="2013">2013</option>
       <option value="2014">2014</option>
       <option value="2015">2015</option>
       <option value="2016">2016</option>
    </select>
   </div>
<label>Start_Time(hr, min):</label>
  <div>
  <select id="start_hour" name="start_hour">
    <% options = []
       (1..12).each do |n|
          timeOption = [n, n]
          options << timeOption
       end %>
     <%= options_for_select(options, 1) %>
  </select>
  </div>
  <div>
  <select id="start_minutes" name="start_minutes">
      <% options = []
       (0..59).each do |n|
          timeOption = [n, n]
          options << timeOption
       end %>
     <%= options_for_select(options, 1) %>
  </select>
  </div>
  <div>
  <select id="start_selection" name="start_selection">
      <option selected value="AM">AM</option>
      <option value="PM">PM</option>
  </select>
  </div>
<label>End_Time(hr, min):</label>
    <div>
    <select id="end_hour" name="end_hour">
    <% options = []
       (1..12).each do |n|
          timeOption = [n, n]
          options << timeOption
       end %>
     <%= options_for_select(options, 1) %>
  </select>
  </div>
  <div>
  <select id="end_minutes" name="end_minutes">
      <% options = []
       (0..59).each do |n|
          timeOption = [n, n]
          options << timeOption
       end %>
     <%= options_for_select(options, 1) %>
  </select>
  </div>
 <div>
  <select id="end_selection" name="end_selection">
      <option selected value="AM">AM</option>
      <option value="PM">PM</option>
  </select></div>
 <label>Description</label><textarea id="description" name="description" class="textarea"></textarea>
<%= hidden_field_tag "recruiter_id", "#{@recruiter.username}" %>
<input type="submit" class="submitForm" id="submitButton" value="Submit">
</form>
<input type="submit" class="submitForm" id="cancelButton" value="Cancel">
<input type="submit" class="deleteButton" id="delete_button" value="Delete"></div>
<script type='text/javascript'>
  $(document).ready(function() {
     $("#cancelButton").click(function() {
           $("#new_event").hide();
     });
      $('#calendar').fullCalendar({
      editable: true,
      selectable: true,
      selectHelper: true,
      events:
      [
          <% @events.each do |event| %>
             <% if not event.name.nil? or event.start_at.nil? or event.end_at.nil? %>
          {
             id : "<%= event.id %>",
             title : "<%= event.name %>",
             start: "<%= event.start_at.iso8601 %>",
             end: "<%= event.end_at.iso8601 %>",
             <% if event.start_at.to_i < Time.now.to_i %>
                className: 'customBlack'
              <% elsif not (event.pending_id.nil? or event.pending_id == "") and not (event.candidate_id.nil? or event.pending_id == "")%>
                className: 'customGreen'
              <% else %>
                className: 'customRed'
             <% end %>
           },
            <% end %>
          <% end %>
      ],
      eventClick: function(calEvent, jsEvent, view) {
            window.location.href = "/event/show/" + calEvent.id;
       },

      select: function(start, end, allDay) {
         $("#new_event").show();
         $("#new_event").attr("action", "/event/create");
         $("#new_event").attr("method", "post");
         var startDate = new Date(start);
         var endDate = new Date(end);
         $("#start_month").val(startDate.getMonth());
         $("#start_date").val(startDate.getDate());
         $("#start_year").val(startDate.getFullYear());
         $("#end_month").val(endDate.getMonth());
         $("#end_date").val(endDate.getDate());
         $("#end_year").val(endDate.getFullYear());
         $("#new_event").draggable();
         $(".submitForm").click(function(){ // on submission
              var title = $(".title").val(); // gets title value
              if(title != ""){ // if the title exists run script
              }
            $(".title").attr("value", "");
            $("#new_event").hide(); // hide pop up box
        });

      },
     unselect: function() {
      },

  });
});

</script>

app/views/recruiters/edit.html.erb
<div class = "row main-page">
  <div class = "small-1 columns user-icon">
    <%= link_to raw('<i class="fi-home profile-icon"></i>'), recruiter_path %>
    <p>Home</p>
    <%= link_to raw('<i class="fi-calendar profile-icon"></i>'), calendar_recruiter_path %>
    <p>Calendar</p>
    <%= link_to raw('<i class="fi-list-thumbnails profile-icon"></i>'), list_recruiter_path, :id=>"List"%>
    <p>Contacts</p>
    <%= link_to raw('<i class="fi-mail profile-icon"></i>'), recruiter_mailbox_path(@recruiter.username, "inbox") %>
    <p>Messages</p>
    <%= link_to raw('<i class="fi-wrench profile-icon active-icon"></i>'), "/recruiters/#{@recruiter.username}/edit", :id=>"Edit"%>
    <p>Settings</p>
  </div>


  <div class = "small-5 columns">
    <div class = "row page-title">
      <div class = "small-12 columns">
        <h2> Settings </h2>
      </div>
    </div>
    <%= content_tag :h4, "Edit page for #{@recruiter.name}" %>
    <%= form_for @recruiter, :html => {:id => "new_recruiter", :multipart => true }, url: "/recruiters/#{@recruiter.username}", method: :put do |f| %>
      <div class="field">
        <%= f.label "Name" %>
        <%= f.text_field :name, :value=>"#{@recruiter.name}" %>
      </div>

    <div class="field">
      <%= f.label "Company" %>
      <%= f.text_field :company, :value=>"#{@recruiter.company}" %>
    </div>
    <div class="field">
        <%= f.label "Email" %>
        <%= f.text_field :email, :value=>"#{@recruiter.email}" %>
    </div>
     <div class ="field">
        <%= f.label "Password" %>
        <%= f.password_field :password, :value=>"#{@recruiter.password}" %>
    </div>
    <div class="field">
        <%= f.label "Location" %>
        <%= f.text_field :location, :value=>"#{@recruiter.location}" %>
    </div>
    <div class="field">
        <%= f.label "Summary" %>
        <%= f.text_field :summary, :value=>"#{@recruiter.summary}" %>
    </div>
     <div class="pic">
       <br/>
       <%= f.label "Picture" %>
       <%= f.file_field :pic %>
       <br/>
     </div>
      <div class="attachment">
        <%= f.label "Attachment" %>
        <%= f.file_field :attach %>
        <br/>
      </div>

     <br/>

     <div class="actions">
       <input type="submit" id="subutton" class="button small alert" value="Update">
     </div>
    <% end %>
  </div>

  <div class = "small-6 columns">
  </div>
</div>

app/views/recruiters/list.html.erb
<div class = "row main-page">
  <div class = "small-1 columns user-icon">
    <%= link_to raw('<i class="fi-home profile-icon"></i>'), recruiter_path %>
    <p>Home</p>
    <%= link_to raw('<i class="fi-calendar profile-icon"></i>'), calendar_recruiter_path(@recruiter.username) %>
    <p>Calendar</p>
    <%= link_to raw('<i class="fi-list-thumbnails profile-icon active-icon"></i>'), list_recruiter_path, :id=>"List"%>
    <p>Contacts</p>
    <%= link_to raw('<i class="fi-mail profile-icon"></i>'), recruiter_mailbox_path(@recruiter.username, "inbox") %>
    <p>Messages</p>
    <%= link_to raw('<i class="fi-wrench profile-icon"></i>'), "/recruiters/#{@recruiter.username}/edit", :id=>"Edit"%>
    <p>Settings</p>
  </div>
  <div class = "large-6 columns">
  <div class = "row page-title">
      <div class = "small-12 columns">
        <h2> List of Associated Candidates </h2>
      </div>
    </div>
    <table id="candidates">
      <tr>
        <th id = "name">Full Name</th>
        <th id = "uname">Username</th>
        <th id = "email">Email</th>
      </tr>
      <% @candidates.each do |candidate|%>
        <tr>
          <td id="name"><%=candidate.name%></td>
          <td id="username"><%=candidate.username%></td>
          <td id="email"><%=candidate.email%></td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class = "large-3 columns search-feature">
  <h3> Associate Candidate </h3>
  <% if flash[:error] %>
    <%= flash[:error] %>
    </br></br>
  <% end %>
  <h6> Add Candidate </h6>
  <%= form_tag("add_candidate", method: "post") do %>
      <%= text_field_tag(:candidate, nil, :id=>"candidate_username") %>
      <%= submit_tag("Add", class: "button small alert")%>
  <% end %>
   <h6> Search by name or username </h6>
  <%= form_tag("search", method: "get") do %>
     <input type="hidden" id="recruiter" name="recruiter" value="<%= @recruiter.username %>">
     <input type="text" id="keyword" name="keyword">
     <input type="submit" class ="button small alert" id="Search" value="Search">
  <% end %>
  </div>
  <div class = "large-2 columns">
  </div>
</div>

app/views/recruiters/mailbox.html.erb
<div class = "row main-page">
  <div class = "small-1 columns user-icon">
    <%= link_to raw('<i class="fi-home profile-icon"></i>'), recruiter_path %>
    <p>Home</p>
    <%= link_to raw('<i class="fi-calendar profile-icon"></i>'), calendar_recruiter_path %>
    <p>Calendar</p>
    <%= link_to raw('<i class="fi-list-thumbnails profile-icon"></i>'), list_recruiter_path, :id=>"List"%>
    <p>Contacts</p>
    <%= link_to raw('<i class="fi-mail profile-icon active-icon"></i>'), recruiter_mailbox_path(@recruiter, "inbox") %>
    <p>Messages</p>
    <%= link_to raw('<i class="fi-wrench profile-icon"></i>'), "/recruiters/#{@recruiter}/edit", :id=>"Edit"%>
    <p>Settings</p>
  </div>

  <div class = "small-8 columns">
  <div class = "row page-title">
      <div class = "small-12 columns">
        <h2> Messages </h2>
      </div>
    </div>

    <div class = "row">
    <div class = "small-12">

    <dl class="sub-nav">
        <dd><a href="/recruiter/<%= @recruiter %>/mailbox/inbox">Inbox</a></dd>
        <dd><a href="/recruiter/<%= @recruiter %>/mailbox/outbox">Outbox</a></dd>
    </dl>
      <% if @type == "inbox" %>

    <% else %>

    <% end %>
    </div>
  </div>
  <div class = "row">
  <div class = "small-12">
  <table id = "mailbox">
    <thead>
      <tr>
        <th id = "messenger"> Messenger </th>
        <th id = "title"> Title </th>
        <th id = "content"> Content </th>
      <tr>
    </thead>
  <tbody>
    <% @mail.each do |mail| %>
      <tr>
        <td>
        <% if @type == "inbox" %>
          <%= mail.from %>
        <% else %>
          <%= mail.to %>
        <% end %>
      </td>
      <td>
      <%= mail.title %>
    </td>
    <td>
      <%= mail.content %>
    </td>
      </tr>
    <% end %>
  </tbody>
  </table>
    </div>
  </div>
  <button class="small button alert" id="compose_button">Compose </a>
  </div>
  <div class = "small-3">
  </div>

</div>

<script>
  $("#compose_button").click( function() {
    window.location.href = "/message/recruiter/" + "<%= @recruiter %>";
  });
</script>

app/views/recruiters/search.html.erb
<div class = "row main-page">
   <div class = "small-1 columns user-icon">
    <%= link_to raw('<i class="fi-home profile-icon"></i>'), recruiter_path %>
    <p>Home</p>
    <%= link_to raw('<i class="fi-calendar profile-icon"></i>'), calendar_recruiter_path %>
    <p>Calendar</p>
    <%= link_to raw('<i class="fi-list-thumbnails profile-icon  active-icon"></i>'), list_recruiter_path, :id=>"List"%>
    <p>Contacts</p>
    <%= link_to raw('<i class="fi-mail profile-icon"></i>'), recruiter_mailbox_path(@recruiter, "inbox")%>
    <p>Messages</p>
    <%= link_to raw('<i class="fi-wrench profile-icon"></i>'), "/recruiters/#{@recruiter}/edit", :id=>"Edit"%>
    <p>Settings</p>
  </div>

  <div class = "small-8 columns">
    <div class = "row page-title">
      <div class = "small-12 columns">
        <h2> Search Results</h2>
      </div>
    </div>
    
    <div class = "row">
	  <div class = "small-12 columns"> 
        <table id="candidates">
          <tr>
      		<th>Full Name</th>
      		<th>Username</th>
      		<th>Email</th>
      		<th>Add</th>    
    	  </tr>
  		  <% @candidates.each do |candidate|%>
    	    <tr>
      		  <%= form_tag("add_recruiter", method: "post") do %>
      		  	<td id="name"><%=candidate.name%></td>
      			<%= hidden_field_tag(:candidate, candidate.username, :id => "candidate_username") %>
      			<td id="username"><%=candidate.username%></td>
      			<td id="email"><%=candidate.email%></td>
      			<td><%= submit_tag("Add", class: "button small") %></td>
      	      <% end %>
    	    </tr>
  		  <% end %>
  		</table>
	  </div>
	</div>

	<div class = "row">
	  <div class = "small-8 columns">
	    <h3> Send an Email Message to a Candidate </h3>
        <%= form_tag("message_candidate", method: "post") do %>
          <%= label_tag(:candidate, "Candidate's Username") %>
          <%= text_field_tag(:candidate) %>
          <%= label_tag(:message, "Your Message") %>
          <%= text_field_tag(:message) %>
          <%= submit_tag("Send", class:"button alert")%>
        <% end %> 	
      </div>
      <div class = "small-4 columns">
	  </div>
	</div>
  </div>

  <div class = "small-3 columns">
  </br></br>   
  <h4> Associate Candidate </h4>
  <% if flash[:error] %>
    <%= flash[:error] %>
    </br></br>
  <% end %>
  <%= form_tag("add_candidate", method: "post") do %>
      <%= label_tag(:candidate, "Candidate's Username") %>
      <%= text_field_tag(:candidate, nil, :id=>"candidate_username") %>
      <%= submit_tag("Add", class: "button alert small") %>
  <% end %>
  <h4>Search</h4>
  <%= form_tag("search", method: "get") do %>
    <%= label_tag("Search by name or username")%>
    <input type="hidden" id="recruiter" name="recruiter" value="<%= @recruiter %>" >
    <input type="text" id="keyword" name="keyword">
    <input type="submit" id="Search" value="Search" class = "button alert small">
  <% end %>

  </div>
  
</div>

app/views/recruiters/show.html.erb
<div class = "row main-page">
   <div class = "small-1 columns user-icon">
    <%= link_to raw('<i class="fi-home profile-icon active-icon"></i>'), recruiter_path %>
    <p>Home</p>
    <%= link_to raw('<i class="fi-calendar profile-icon"></i>'), calendar_recruiter_path %>
    <p>Calendar</p>
    <%= link_to raw('<i class="fi-list-thumbnails profile-icon"></i>'), list_recruiter_path, :id=>"List"%>
    <p>Contacts</p>
    <%= link_to raw('<i class="fi-mail profile-icon"></i>'), recruiter_mailbox_path(@recruiter.username, "inbox")%>
    <p>Messages</p>
    <%= link_to raw('<i class="fi-wrench profile-icon"></i>'), "/recruiters/#{@recruiter.username}/edit", :id=>"Edit"%>
    <p>Settings</p>
  </div>

  <div class = "small-11 columns">
    <div class = "row page-title">
      <div class = "small-12 columns">
        <h2> Dashboard </h2>
      </div>
    </div>

    <div class = "row">
      <div class = "small-5 columns">
    <div class = "row profile-view">
      <div class = "small-6 columns">
            <%= image_tag @recruiter.pic.url(:thumb), id: "profile-picture" %>
      </div>
      <div class = "small-6 columns profile-info">
        <div class = "panel">
        <h5>Username</h5>
        <h6><%= @recruiter.username %></h6>
        <h5>Name</h5>
        <h6><%= @recruiter.name %></h6>
        <h5>Company</h5>
        <h6><%= @recruiter.company %></h6>
		<h5>Location</h5>
		<h6><%= @recruiter.location %></h6>
        </div>
      </div>
    </div>
    <div class = "row">
      <div class = "small-12 columns profile-info-summary">
        <div class = "panel">
			<h5>Summary </h5>
			<h6><%= @recruiter.summary %></h6>
        </div>


      </div>
    </div>

      </div>

      <div class = "small-7 columns ">
    
    <div class = "row">
      <div class = "small-12 columns">
        <h4> Upcoming Events </h4>
            <% if @events.empty? %>
              <p> No upcoming events </p>
            <% else %>

        <table id="show-events">
        <thread>
          <tr>
            <th>Event Title</th>
            <th>Candidate</th>
            <th>Status</th>
            <th>Date</th>
            <th>Details</th>
          </tr>
        </thread>
        <tbody>
                <% @events.each do |event|%>
          <% request_info = show_event_info(event, event.pending_id)%>
                  <tr>
                    <td><%= request_info[0] %></td>
          <td><%= request_info[1] %></td>
          <td><%= request_info[2] %></td>
          <td><%= request_info[3] %></td>
                    <td>
            <a class="small button" href="/event/show/<%=event.id%>?from_id=<%=@recruiter.username%>">Details</a>
            </td>
                  </tr>
                <% end %>
        </tbody>
              </table>

            <% end %>
      </div>
    </div>
      </div>

    </div>
  </div>
</div>

app/views/recruiters/show.html.haml
%h3 Recruiter Profile View
%h3 Welcome, #{@recruiter.password}
%h3 Your email address is: #{@recruiter.email}